language: python
sudo: required
services:
  mongodb
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - pytest tests/
